#!/usr/bin/env bash

eget -a 'amd64_linux' --to=upx upx/upx
eget -a 'linux_amd64.tar.gz' --to=curlie rs/curlie
eget -a 'linux_amd64' --to=procs junegunn/fzf
eget -a 'Linux_x86_64' --to=lazydocker jesseduffield/lazydocker
eget -a 'linux-amd64' --to=dry moncho/dry
eget -a 'linux64-static' --to micro zyedidia/micro
eget -a 'nerd-static' --to=nnn jarun/nnn
eget -a 'x86_64-linux' --to=procs dalance/procs
eget -a 'x86_64-unknown-linux-musl.tar.xz' -a '^sha' -a '^b3' --to=watchexec watchexec/watchexec
eget -a 'x86_64-unknown-linux-musl' --to starship starship/starship
eget -a 'x86_64-unknown-linux-musl' --to=dust bootandy/dust
eget -a 'x86_64-unknown-linux-musl' --to=ouch ouch-org/ouch
eget -a 'x86_64-unknown-linux-musl' --to=zellij zellij-org/zellij
eget -a 'x86_64-unknown-linux-musl' --to=zoxide ajeetdsouza/zoxide
eget -a dasel_linux_amd64 --to=dasel TomWright/dasel
eget -a dprint-x86_64-unknown-linux-gnu --to=dprint dprint/dprint
eget -a exa-linux-x86_64-v --to=exa ogham/exa
eget -a gdu_linux_amd64.tgz --to=gdu dundee/gdu
eget -a jq-linux64 --to=jq stedolan/jq
eget -a linux -a 4.14 bcpierce00/unison
eget -a linux_amd64 --to=pup ericchiang/pup
eget -a linux_x86_64 --to=crawley s0rg/crawley
eget -a linux-amd64 --to=ctop bcicen/ctop
eget -a linux-amd64 --to=gron tomnomnom/gron
eget -a task_linux_amd64.tar.gz --to=task go-task/task
eget -a x86_64 -a linux --to=rg BurntSushi/ripgrep
eget -a x86_64-linux --to=htmlq mgdm/htmlq
eget -a x86_64-unknown-linux --to=checkexec kurtbuilds/checkexec
eget -a x86_64-unknown-linux-gnu --to=bat sharkdp/bat
eget -a x86_64-unknown-linux-gnu --to=bkt dimo414/bkt
eget -a x86_64-unknown-linux-gnu --to=fd sharkdp/fd
eget -a x86_64-unknown-linux-gnu --to=sd chmln/sd
eget -a x86_64-unknown-linux-gnu --to=tokei XAMPPRocky/tokei
eget -a x86_64-unknown-linux-musl --to=just casey/just

eget https://raw.githubusercontent.com/Chaostheorie/sponge/main/sponge &
eget https://raw.githubusercontent.com/ryanwoodsmall/static-binaries/master/x86_64/busybox &
eget https://raw.githubusercontent.com/ryanwoodsmall/static-binaries/master/x86_64/curl &
eget https://raw.githubusercontent.com/ryanwoodsmall/static-binaries/master/x86_64/pv &
eget https://raw.githubusercontent.com/ryanwoodsmall/static-binaries/master/x86_64/rsync &
eget https://raw.githubusercontent.com/ryanwoodsmall/static-binaries/master/x86_64/xml &
eget https://raw.githubusercontent.com/ryanwoodsmall/static-binaries/master/x86_64/xmllint &
eget https://raw.githubusercontent.com/ryanwoodsmall/static-binaries/master/x86_64/entr &
eget https://raw.githubusercontent.com/ryanwoodsmall/static-binaries/master/x86_64/jo &

wait

# Find all executable ELF files
find . -maxdepth 1 -type f -executable | xargs file | grep ELF | sort | cut -d ':' -f1 | xargs sha256sum >| SHASUM

# Exclude some files
cat ./SHASUM | egrep -v 'watchexec|upx|gdu|zellij|starship|entr' >| /tmp/SHASUM.tmp

# UPX only changed files
sha256sum --check /tmp/SHASUM.tmp --quiet 2> /dev/null | cut -d ':' -f 1 | xargs -I '{}' bash -c 'upx --best "{}"'
